---
server:
  update_interval: 2
segments:
  - name: left
    bg_palette:
      - "#f5e0dc"
      - "#f5c2e7"
      - "#cba6f7"
      - "#eba0ac"
      - "#f9e2af"
      - "#a6e3a1"
      - "#94e2d5"
      - "#89dceb"
      - "#89b4fa"
      - "#b4befe"
    fg_palette:
      - "#11111b"
      - "#181825"
      - "#1e1e2e"
    separator: 
    parts:
      - type: session_name
        template: ": {{v}}"
      - type: mem
        template: ": {{v.total}}/{{v.available}}/{{v.used}} {{v.used_percents}}% {{v.used_percents_graph}}"
      - type: cpu
        # Where v is a string value without percent symbol
        template: ": {{v.consumption}}% {{v.consumption_graph}}"
      - type: disk
        dev: /dev/mapper/luks-7a504a5c-d5f0-4175-95b6-3a97c15a21ce
        # Where v is a structure with
        template: " {{v.mount_point}} {{v.used_percents}}%"
  - name: right
    bg_palette:
      - "#f5e0dc"
      - "#f5c2e7"
      - "#cba6f7"
      - "#eba0ac"
      - "#f9e2af"
      - "#a6e3a1"
      - "#94e2d5"
      - "#89dceb"
      - "#89b4fa"
      - "#b4befe"
    fg_palette:
      - "#11111b"
      - "#181825"
      - "#1e1e2e"
    separator: 
    direction: rtl
    parts:
      - type: load_average
        template: "LA: {{v.one}}, {{v.five}}, {{v.fifteen}}"
