---
name: Cargo

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'    
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
