---
name: Release binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v2

  build-and-bundle-binaries:
    needs: setup
    runs-on: self-hosted
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - name: Build ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
      - name: Bundle ${{ matrix.target }}
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "${{contains(matrix.target, 'apple') && 'zip' || 'tar'}}"
          directory: "target/${{ matrix.target }}/release/"
          filename: "rusty-belt-${{github.ref_name}}-${{ matrix.target }}.${{ contains(matrix.target, 'apple') && 'zip' || 'tar.gz' }}"
          exclusions: "build deps examples incremental *.d *.rlib .fingerprint .cargo-lock"
  publish-to-release:
    runs-on: self-hosted
    needs: build-and-bundle-binaries
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rusty-belt-${{github.ref_name}}-x86_64-apple-darwin.zip
            rusty-belt-${{github.ref_name}}-aarch64-apple-darwin.zip
            rusty-belt-${{github.ref_name}}-x86_64-unknown-linux-musl.tar.gz
            rusty-belt-${{github.ref_name}}-aarch64-unknown-linux-musl.tar.gz
