---
name: Release binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  runs-on: self-hosted
  strategy:
    matrix:
      target:
        - x86_64-apple-darwin
        - aarch64-apple-darwin
        - aarch64-unknown-linux-musl
        - x86_64-unknown-linux-musl
  steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Build ${{ matrix.target }}
      run: cargo build --release --target ${{ matrix.target }}
    - name: Bundle ${{ matrix.target }}
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: contains(matrix.target, 'apple') && "zip" || "tar"
        directory: "target/${{ matrix.target }}/release"
        filename: "rusty-belt-${{github.ref_name}}-${{ matrix.target }}.${{ contains(matrix.target, 'apple') && 'zip' || 'tar' }}"
        exclusions: "build deps examples incremental *.d *.rlib"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          LICENSE
